config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get 'signup', to: 'users#new'
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  delete 'logout', to: 'sessions#destroy'
  resources :clients
  resources :services
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
 has_and_belongs_to_many :services
  validates :phone_number, presence: true, numericality: true, length: { is: 9 }

  def self.send_mail
    NotificationMailer.notification_mailer( @client ).deliver
  end
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :clients
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  before_validation { self.email = self.email.downcase }

  validates :username, presence: true, length: { maximum: 25 }, uniqueness: { case_sensetive: false }
  validates :email, presence: true, length: { maximum: 40 }, uniqueness: { case_sensetive: false }, format: { with: VALID_EMAIL_REGEX }
  validates :password,presence: true

  has_many :clients, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find( session[:user_id] ) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_services, except: [:destroy]
  def index
    @clients = Client.where(user: current_user)
  end

  def new
    @client = Client.new
  end

  def show
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    @client.user = current_user
    if @client.save
      #check mailer is working or not
      #NotificationMailer.notification_mailer( @client ).deliver
      redirect_to @client

    else
      render 'new'
    end
  end


  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    if @client.destroy
      flash[:notice] = "Client is deleted"
    end

    redirect_to clients_path
  end

  private
  def client_params
    params.require( :client ).permit( :name, :address, :phone_number,:email , service_ids: [])
  end
  def set_services
    @services = Service.where(user: current_user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_services
  def index
    @services = Service.where(user: current_user)
  end

  def new
    @service = Service.new
  end


  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to services_path
    else
      render 'new'
    end
  end


  def destroy
    @service = Service.find(params[:id])
    if @service.destroy
      flash[:notice] = "Service is deleted"
    end

    redirect_to services_path
  end

  private
  def service_params
    params.require( :service ).permit( :name, :price)
  end
  def set_services
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    return unless logged_in?

    flash[:warning] = "You have already logged in."
    redirect_to root_path
  end

  def create
    user = User.find_by( email: params[ :session ][ :email ].downcase )
    if user && user.authenticate( params[ :session ][ :password ] )
      session[:user_id] = user.id
      flash[:notice] = " Logged in Successfully "
      redirect_to root_path
    else
      flash.now[:notice] = " There was something wrong with your login details "
      render "new"
    end
  end


  def destroy
    if logged_in?
      session[ :user_id ] = nil
      flash[ :notice ] = " Logged Out "
      redirect_to root_path
    else
      flash[ :notice ] = " You are not logged in "
      redirect_to login_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [ :show, :edit, :update ]


  def new
   if logged_in?
     flash[:warning] = "You have already logged in."
     redirect_to root_path
     return
   end

   @user = User.new
  end

  def edit
  end

  def show
  end

  def create
   @user = User.new( user_params )
   if @user.save
     session[:user_id] = @user.id
     flash[:notice] = " Hello,  #{ @user.username } "
     redirect_to root_path
   else
     render "new"
   end
  end

  def update
   if @user.update(user_params)
     flash[:notice] = " ACCOUNT IS UPDATED "
     redirect_to root_path
   else
     render "edit"
   end
  end

  private

   def user_params
     params.require( :user ).permit( :username, :email, :password, :password_confirmation )
   end

   def set_user
       @user = User.find( params[:id] )
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: @client, html: {class: "ui large form"}, local: true) do |form| %>
  <h4 class = "ui dividing header">Client Information</h4>
  <div class = "field">
    <label><%= form.label :name, "Name" %></label>
    <div class = "fields">
      <div class = "twelve wide field">
         <%= form.text_field :name, placeholder: "Name", class: "border border-success", :required => true %>
      </div>
    </div>
  </div>
  <div class = "field">
    <span class = "font-weight-bold"><%= form.label :email, "Email"%></span>
    <span class = "text-danger">*</span>
    <%= form.email_field :email, placeholder: "Email", class: "border border-success", :required => true %>
  </div>
  <div class = "field">
    <label> <%= form.label :address, "Address" %></label>
    <div class = "fields">
      <div class = "twelve wide field">
         <%= form.text_field :address, placeholder: "Address", class: "border border-success", required: true %>
      </div>
    </div>
  </div>
  <p>Enter only 9 digits</p>
  <div class = "field">
    <label> <%= form.label :phone_number, "Contact Number" %></label>
    <div class = "fields">
      <div class = "two wide field bg-success text-right text-white p-2 ml-2">
        +91
      </div>
      <div class = "ten wide field">
        <%= form.text_field :phone_number, placeholder: "Number without 0 or +91 (eg. 89xxxxxxxx )", class: "border border-success", :required => true %>
      </div>
    </div>
  </div>
<br>
  <div class="field">
    <h3> <%= form.label :services, "Services" %></h3><br/>
    <%= form.collection_check_boxes :service_ids, @services, :id, :name do |b|%>
    <%= b.check_box(class: "check_box") %>
    <%= b.label(class: "check_box") %>
    <br/>
    <% end %>
  </div>

  <%= form.submit @client.new_record? ? "SAVE" : "UPDATE", class: "ui green button m-2"%>

<% end %>

app/views/clients/edit.html.erb
<h1 class = "text-center" >Edit client</h1>
<%= render "shared/errors",obj: @client %>
<%= render "form" %>

app/views/clients/index.html.erb
<h1>Listing Clients</h1>

<table>
  <tr>
    <th class = "p-2">Name</th>
    <th class = "p-2">Address</th>
    <th class = "p-2">Phone Number</th>
    <th colspan="2"></th>
  </tr>

  <% @clients.each do |client| %>
    <tr>
      <td class = "p-2"><%= client.name %></td>
      <td class = "p-2"><%= client.address %></td>
      <td class = "p-2"><%= client.phone_number %></td>
      <td class = "p-2"><%= link_to 'Show', client_path(client) %></td>
      <td class = "p-2"><%= link_to 'Edit', edit_client_path(client) %></td>
      <td class = "p-2"><%= link_to 'Destroy', client_path(client), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/clients/new.html.erb
<h1 class = "text-center">Add Client</h1>
<%= render "shared/errors",obj: @client %>
<%= render "form" %>

app/views/clients/show.html.erb
<h4>Name :- <%= @client.name %></h4>
<h4>address :- <%= @client.address %></h4>
<h4>phone_number :- <%= @client.phone_number %></h4>
<h4>phone_number :- <%= @client.email %></h4>
<h4>Services</h4>

<% @client.services.each do |service| %>
<p><%= service.name %> </p>

<%end%>

app/views/home/index.html.erb
<h1>WELCOME</h1>
<% if logged_in? %>
<h1>hello, <%= current_user.username %></h1>
<% end %>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class = "alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role = "alert">
      <%= msg %>
      <button type = "button" class = "close" data-dismiss = "alert" aria-label = "Close">
        <span aria-hidden = "true">&times;</span>
      </button>
    </div>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
<div class = "container">
  <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarSupportedContent" aria-controls = "navbarSupportedContent" aria-expanded = "false" aria-label = "Toggle navigation">
    <span class = "navbar-toggler-icon"></span>
  </button>
  <div class = "collapse navbar-collapse" id = "navbarSupportedContent">
    <ul class = "navbar-nav ml-auto">
      <li class = "nav-item active">
        <%= link_to "Home", root_path, class:"nav-link"%>
      </li>
      <% if logged_in? %>
      <li class = "nav-item active">
        <%= link_to "All clients", clients_path, class:"nav-link"%>
      </li>
      <li class = "nav-item active">
        <%= link_to "New Client", new_client_path, class:"nav-link"%>
      </li>
      <li class = "nav-item active">
        <%= link_to "All services", services_path, class:"nav-link"%>
      </li>
      <li class = "nav-item active">
        <%= link_to "New Service", new_service_path, class:"nav-link"%>
      </li>
      <% end %>

      <li class = "nav-item dropdown ">
        <a class = "nav-link dropdown-toggle" href = "#" id = "navbarDropdown" role = "button" data-toggle = "dropdown" aria-haspopup = "true" aria-expanded = "false">
          Account
        </a>
        <div class = "dropdown-menu" aria-labelledby = "navbarDropdown">
          <% if logged_in? %>
              <%= link_to current_user.username, user_path(current_user), class: "dropdown-item"%>
                    <div class = "dropdown-divider"></div>
              <%= link_to "Log out", logout_path, class: "dropdown-item", method: :delete%>
          <% else %>
              <%= link_to "SignUp", signup_path, class: "dropdown-item"%>
              <%= link_to "Log In", login_path, class: "dropdown-item"%>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LawFirm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navigation"%>
  <div class="container">
    <%= render "layouts/messages" %>
    <%= yield %>
  </div>

  </body>
</html>

app/views/services/_form.html.erb
<%= form_with(model: @service, html: {class: "ui large form"}, local: true) do |form| %>
  <h4 class = "ui dividing header">Service Information</h4>
  <div class = "field">
    <label><%= form.label :name, "Name" %></label>
    <div class = "fields">
      <div class = "twelve wide field">
         <%= form.text_field :name, placeholder: "Name", class: "border border-success", :required => true %>
      </div>
    </div>
  </div>
  <div class = "field">
    <label> <%= form.label :price, "price" %></label>
    <div class = "fields">
      <div class = "twelve wide field">
         <%= form.text_field :price, placeholder: "Price", class: "border border-success", required: true %>
      </div>
    </div>
  </div>


  <%= form.submit  "SAVE" , class: "ui green button m-2"%>

<% end %>

app/views/services/index.html.erb
<h1>Listing Services</h1>

<table>
  <tr>
    <th class = "p-2">Name</th>
    <th class = "p-2">Price</th>
    <th colspan="2"></th>
  </tr>

  <% @services.each do |service| %>
    <tr>
      <td class = "p-2"><%= service.name %></td>
      <td class = "p-2"><%= service.price %></td>
      <td class = "p-2"><%= link_to 'Destroy', service_path(service), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/services/new.html.erb
<h1 class = "text-center">Add Service</h1>
<%= render "shared/errors",obj: @service %>
<%= render "form" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class = "alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class = "alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class = "close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, html: {class: "ui form"}, local: true) do |form| %>
  <div class = "field">
    <span class = "font-weight-bold"><%= form.label :username, "Username"%></span>
    <span class = "text-danger">*</span>
    <%= form.text_field :username, placeholder: "Username", class: "border border-success", :required => true %>
  </div>
  <div class = "field">
    <span class = "font-weight-bold"><%= form.label :email, "Email"%></span>
    <span class = "text-danger">*</span>
    <%= form.email_field :email, placeholder: "Email", class: "border border-success", :required => true %>

  </div>
  <div class = "field">
    <span class = "font-weight-bold"><%= form.label :password, "Password"%></span>
    <span class = "text-danger">*</span>
    <%= form.password_field :password, placeholder: "Password", class: "border border-success", :required => true %>
  </div>
  <div class = "field">
    <span class = "font-weight-bold"><%= form.label :password, "Password Confirmation"%></span>
    <span class = "text-danger">*</span>
    <%= form.password_field :password_confirmation, placeholder: "Password Confirmation", class: "border border-success", :required => true %>
  </div>
  <%= form.submit @user.new_record? ? "SIGN UP" : "UPDATE", class: "ui button green"%>

<% end %>

app/views/users/edit.html.erb
<h1 class = "text-center">EDIT <%= @user.class %></h1>
<%= render "shared/errors", obj: @user %>
<%= render "form" %>

app/views/users/new.html.erb
<h1 class = "text-center">Sign UP</h1>
<%= render "shared/errors", obj: @user %>
<%= render "form" %>
<div class="text-danger text-right">
  Please fill the filed marked with *
</div>

app/views/users/show.html.erb
<h1 class = "text-center">HELLO, <%= @user.username %></h1>

<table class = "table">
  <tr>
    <th scope="col">User Name</th>
    <td scope="row"><%= @user.username %></td>
  </tr>
  <tr>
    <th scope="col">Email</th>
    <td scope="row"><%= @user.email %></td>
  </tr>
</table>

  <div class = "ui primary button">
    <%= link_to "Edit User Details", edit_user_path(@user) ,class: "text-white"%>
    <i class = "right chevron icon"></i>
  </div>